In [10]:
import pandas as pd
import numpy as np

In [5]:
rent_6_9 = pd.read_csv("E:\\bikeshare\\resources\\data_set\\pred_rent_60min_06_09.csv")

In [6]:
rent_6_9

1   2   3   4   5    6   7   8   9  10  ...  291  292  293  294  295  296  \
0   4   4   5   3   9    2   3   4   8  13  ...    1    4    0   14   17    4   
1  15  23  41  11   7   33  26  31  21  63  ...   17   20    8   73   34   37   
2  70  10  49   6  21  106  31  42  19  85  ...   88   80    3   53   27   53   

   297  298  299  300  
0    2    8    1    3  
1    5    5    0    6  
2   23   25    2   19  

[3 rows x 300 columns]

In [8]:
rent_6_9.to_numpy()

array([[  4,   4,   5,   3,   9,   2,   3,   4,   8,  13,   2,   3,  12,
          0,   3,   2,   3,   3,   0,   6,  17,   4,   3,   0,   5,   4,
          5,   4,   1,   5,   3,   2,   2,   2,   3,   3,   3,   8,   7,
         21,   7,  17,  10,   3,   5,   4,   5,   4,   6,   3,   3,  13,
          5,   8,   1,   1,   6,  13,   2,   2,   7,   9,   7,   0,   7,
         12,   4,   8,   2,   9,   8,   7,   2,   5,   4,   5,   7,   3,
          1,   6,   3,  13,   5,   1,   6,   1,   9,   0,   6,   0,   2,
          5,   2,   5,   3,  17,  15,   3,   1,   2,  38,  11,   1,   1,
          3,   1,   0,   4,   9,   3,   4,   3,  11,   7,   3,   0,  10,
          3,   4,   7,   5,   4,   1,   9,   9,  48,   0,   8,   7,   2,
          8,   7,   4,   1,   0,   0,   7,   2,   4,   6,   0,   5,   1,
          2,   7,  24,   7,   3,   2,   0,   6,   6,   1,   3,   4,   5,
          7,  10,   3,   0,   3,   2,   2,   6,   2,   1,   3,   3,   6,
          3,  18,   3,   2,   3,   1,   2,   6,   7

In [11]:
rent_6_9 = np.array([[  4,   4,   5,   3,   9,   2,   3,   4,   8,  13,   2,   3,  12,
          0,   3,   2,   3,   3,   0,   6,  17,   4,   3,   0,   5,   4,
          5,   4,   1,   5,   3,   2,   2,   2,   3,   3,   3,   8,   7,
         21,   7,  17,  10,   3,   5,   4,   5,   4,   6,   3,   3,  13,
          5,   8,   1,   1,   6,  13,   2,   2,   7,   9,   7,   0,   7,
         12,   4,   8,   2,   9,   8,   7,   2,   5,   4,   5,   7,   3,
          1,   6,   3,  13,   5,   1,   6,   1,   9,   0,   6,   0,   2,
          5,   2,   5,   3,  17,  15,   3,   1,   2,  38,  11,   1,   1,
          3,   1,   0,   4,   9,   3,   4,   3,  11,   7,   3,   0,  10,
          3,   4,   7,   5,   4,   1,   9,   9,  48,   0,   8,   7,   2,
          8,   7,   4,   1,   0,   0,   7,   2,   4,   6,   0,   5,   1,
          2,   7,  24,   7,   3,   2,   0,   6,   6,   1,   3,   4,   5,
          7,  10,   3,   0,   3,   2,   2,   6,   2,   1,   3,   3,   6,
          3,  18,   3,   2,   3,   1,   2,   6,   7,  10,  31,   5,   3,
          9,   0,  16,   3,   9,   8,   4,   8,   5,   9,   8,   8,   4,
          1,   6,   9,   1,   3,   5,   2,   6,   5,   2,   2,   5,   3,
          2,   9,   3,  14,   5,   5,  10,  15,   5,   3,   3,   6,   4,
         19,   7,   2,   6,   7,   5,   1,   7,  10,   4,   6,  11,   4,
          4,  25,   3,   3,  15,  12,   5,  11,   7,   4,   5,   3,   2,
          4,   5,  13,   4,   6,   4,   3,   4,   0,   6,   2,   3,   7,
          8,   5,   5,   6,  14,   5,   2,   2,   6,  10,   6,  19,   3,
         18,  10,   2,   3,   5,   2,   0,   2,   3,   0,   1,  14,  16,
          3,   6,   3,   2,   1,   4,   0,  14,  17,   4,   2,   8,   1,
          3],
       [ 15,  23,  41,  11,   7,  33,  26,  31,  21,  63,  11,  17,  13,
          5,  13,  30,  27,  17,   7,  21,  43,   8,  11,   5,  20,  23,
         13,  31,   6,   4,   6,   9,   5,  17,   6,   2,  11,  73,  15,
        113,   9,  59,  26,  11,  10,  27,  13,  12,  18,  10,  18,  35,
         23,  19,  16,  12,  18,  23,   2,  17,  26,  12,  22,   4,  21,
         28,  23,  24,   6,  48,   4,  17,   4,  16,  25,  11,  73,  14,
          7,  20,   4,  38,   7,   7,  15,   3,  19,  20,   9,  12,  22,
         10,   8,   7,  20,  64,  44,  11,   6,  26,  85,  18,  18,   4,
          8,  31,   7,  13,  20,  11,  26,  10,  27,  22,  12,   6,  17,
         16,  22,  26,  26,   8,   9,  35,  37, 182,   6,  14,  10,  20,
         19,  56,  27,   9,  23,   8,  17,   1,  33,  15,   5,  33,   5,
         23,  21,  82,  12,  37,   3,   1,  18,  17,   9,  18,  26,  35,
          8,  35,  22,   8,  13,  22,   6,  15,   5,   6,   7,   9,  26,
         18,  65,  17,  12,  18,   9,  23,  16,  32,  14, 101,  18,  35,
         19,   7,  73,  13,  13,  12,  26,  56,  26,  14,  40,  11,  35,
         11,  13,  18,   6,  11,  33,  13,  33,  12,  15,   9,  12,  16,
         13,  36,  10,  13,  20,  13,  37,  74,   8,  28,  17,  44,  16,
         86,  40,   5,  28,  30,  22,   6,  21,  47,   5,  39,  66,  20,
          8,  43,   8,   7,  34,  63,  15,  28,  23,  10,  20,  23,  13,
          5,  19,  25,  53,   7,   8,   4,  13,  10,  45,  15,  11,  27,
         14,  50,  36,  15,  69,  37,  20,   4,  20,  18,  11,  72,   7,
         32,  33,  16,   8,  18,   0,   7,  54,  11,  14,   9,  60,  34,
         11,  28,  24,   5,  17,  20,   8,  73,  34,  37,   5,   5,   0,
          6],
       [ 70,  10,  49,   6,  21, 106,  31,  42,  19,  85,   7,  52,  13,
         16,  48,  30,  21,  44,  37,  77,  42,  17,  53,  29,  55,  66,
         16,  28,   7,  14,   6,  62,  20,  27,  22,   5,   9,  24,  10,
        131,   3,  40,  52,  11,  20,  36,  10,  58,  29,  13,  39,  19,
         48,  34,  67,   9,  26,  25,   2,  17,  25,  19,  46,   7,  30,
         42,  16,  24,  10, 140,   2,  29,  19,  41,  53,  13,  38,  14,
          5,  45,  13,  25,   8,  18,  76,   8,  34,  40,  36,  33,  69,
         43,  14,  32,  39,  47,  47,  13,   5,  46,  83,  15,   9,   9,
         13,  75,   7,  42,  27,  39,  38,  46,  26,  70,  11,   5,  31,
         46,  63,  74, 132,   5,  26,  67,  43, 187,   5,   9,  15,  48,
         20,  48,  31,  29,  97,  16,  31,  10,  38,  27,   8,  18,   8,
         26,  42,  66,  13,  29,   2,   1,  20,  36,   5,  26,  45,  64,
         14,  28,  54,  48,  53,  78,  13,  14,  19,  30,  22,  16,  81,
         16,  79,  19,  26,  22,  11,  29,  10,  45,  27,  94,  17, 102,
         32,   9,  37,  49,  14,   5,  86,  90,  69,  11,  94,  48, 107,
         28,  26,  59,  15,  30,  16,  27,  38,   9,  37,  20,  16,  14,
         30,  97,   9,  26,  32,  20,  82,  61,  15,  16,  48,  46,  12,
         94,  95,   4,  79,  14,  51,   7,  29,  54,   4,  29,  57,  15,
          8,  35,  30,   8,  33,  89,  19,  56,  62,  15,  41,  37,  17,
          6,  16,  33, 173,  20,  26,   7,  21,  25,  44,  45,  16,  43,
         22,  95,  19,  15,  56,  86,  62,   6,  38,  14,  31,  57,  14,
         57,  59,  72,   5,  45,   4,  40,  60,  20,  78,   9,  45,  27,
         53,  43,  61,  55,  88,  80,   3,  53,  27,  53,  23,  25,   2,
         19]])

In [15]:
return_6_9 = pd.read_csv("E:\\bikeshare\\resources\\data_set\\pred_return_60min_06_09.csv").to_numpy()

In [16]:
return_6_9

array([[  3,   5,   4,   1,   2,   4,   4,   3,   4,   5,   3,   4,  13,
          0,   3,   1,   9,   7,   5,   1,   9,   6,   0,   0,   5,   5,
          4,   3,   2,   0,   1,   5,   2,   9,  13,   4,   9,   4,   2,
          5,   4,   5,  11,   1,   6,   6,   7,   1,   2,   2,   4,   7,
          8,  10,   7,   0,   3,  10,   2,   2,   7,   5,   3,   5,   1,
         11,   7,   8,   2,   1,   7,   1,   1,   6,  10,   1,   1,   3,
          1,   2,   2,   2,   9,   7,   8,   0,   3,   2,   8,   2,   4,
          0,   1,   4,   6,   8,   8,   8,   5,   6,  12,  11,   6,   8,
          3,   4,   4,   0,   2,   4,   2,   6,   8,   7,   5,   1,   2,
          0,   0,   6,  14,   2,  11,   4,   5,   8,   2,   7,   4,   2,
          8,   0,   1,   3,   9,   1,   3,   6,   7,   1,   2,   1,   3,
          6,   8,   4,   8,   6,   2,   1,   2,   9,   2,   5,  14,   1,
          6,   8,   0,   2,   8,   0,   4,  12,   4,   2,   6,   1,   2,
         11,   2,   4,   2,   5,   2,   0,   7,   8

In [18]:

max_capacity = pd.read_csv("E:\\bikeshare\\resources\\data_set\\max_capacity.csv").to_numpy()

In [20]:
max_capacity = np.transpose(pd.read_csv('E:\\bikeshare\\resources\\data_set\\max_capacity.csv', header=0, usecols=[1, 2, 3]).
                             to_numpy()).reshape((3, 300))

In [23]:
max_capacity[0][0]

57

In [48]:
cluster_24 = pd.read_csv("E:\\bikeshare\\resources\\data_set\\cluster_station_Thursday_24.csv")

In [49]:
pd.set_option('display.max_rows', 300)
cluster_24[cluster_24['cluster']==0]

station_id  cluster   longitude   latitude  demand
0             1        0  118.787516  32.049756      27
4             5        0  118.797601  32.042453      54
8             9        0  118.798018  32.055706     -26
19           20        0  118.788293  32.043241      16
20           21        0  118.795325  32.048728      -7
28           29        0  118.804457  32.052400      17
38           40        0  118.795020  32.040979      85
41           43        0  118.801678  32.047231      22
43           45        0  118.805545  32.058268      15
45           47        0  118.795072  32.052469      -3
46           48        0  118.791430  32.055973     -16
52           54        0  118.800749  32.040213     -23
61           63        0  118.784530  32.043786     -10
63           65        0  118.793367  32.036921      13
65           67        0  118.793112  32.046766     -31
70           72        0  118.782066  32.049985     -10
78           80        0  118.794517  32.056203      16
81           83        0  118.799687  32.052429     -28
83           85        0  118.788979  32.039022     -28
90           92        0  118.787097  32.054063      10
92           94        0  118.799179  32.047877     -16
99          101        0  118.783886  32.050260     -25
100         102        0  118.790331  32.051390     -27
102         104        0  118.800161  32.060115     -30
117         120        0  118.804201  32.046815     -10
121         124        0  118.784125  32.047698      49
136         139        0  118.796562  32.038877      -1
141         144        0  118.792511  32.052239       6
144         147        0  118.802207  32.044087      -2
148         151        0  118.802360  32.057568      -2
152         155        0  118.792537  32.049239     -42
156         159        0  118.790557  32.041517      -7
159         162        0  118.788171  32.041073       6
164         167        0  118.797047  32.053526     -71
167         170        0  118.794793  32.045072     -70
171         174        0  118.791563  32.038274     -29
179         182        0  118.786269  32.045547      37
183         186        0  118.807082  32.052795      28
185         188        0  118.801703  32.054493     -51
187         190        0  118.784448  32.054398      47
189         192        0  118.799917  32.045561     -36
192         195        0  118.789462  32.049351      63
196         199        0  118.788857  32.055572     -17
202         205        0  118.787458  32.052079     -54
208         211        0  118.799123  32.038248      -8
209         212        0  118.790440  32.047616     -49
210         213        0  118.803425  32.040563      -6
211         214        0  118.795443  32.046731       2
215         218        0  118.795397  32.036802     -19
216         219        0  118.786110  32.041412      27
221         224        0  118.799033  32.049946     -15
224         227        0  118.791046  32.045961     -44
227         230        0  118.795976  32.050551      30
233         236        0  118.794852  32.042828      61
238         241        0  118.787616  32.047928     -51
242         245        0  118.789664  32.053923     -17
243         246        0  118.796055  32.057014     -14
246         249        0  118.802051  32.037552     -23
248         251        0  118.790593  32.044144      61
250         253        0  118.798118  32.046014     -35
255         258        0  118.797521  32.040547      42
268         271        0  118.786965  32.056631     -51
269         272        0  118.784239  32.051823      38
271         274        0  118.796718  32.048593      -7
272         275        0  118.794700  32.039573      71
273         276        0  118.783524  32.045926      62
278         281        0  118.793961  32.053836      11
285         288        0  118.793158  32.040870      -9
287         290        0  118.787392  32.038422      51
289         292        0  118.786013  32.050721      43
292         295        0  118

In [62]:
complete_dict = cluster_24.T.to_dict().values()

In [63]:
station_info_dict = []
station_info = {}
for item in complete_dict:
    tmp = dict(item)
    tmp.pop('station_id')
    station_info[int(item['station_id'])] = tmp
    station_info_dict.append(station_info)

In [64]:
station_info

{1: {'cluster': 0.0,
  'longitude': 118.78751640000002,
  'latitude': 32.04975586,
  'demand': 27.0},
 2: {'cluster': 1.0,
  'longitude': 118.7798845,
  'latitude': 32.02845916,
  'demand': -7.0},
 3: {'cluster': 2.0,
  'longitude': 118.76809159999999,
  'latitude': 32.0665767,
  'demand': 6.0},
 4: {'cluster': 1.0,
  'longitude': 118.7977513,
  'latitude': 32.0150942,
  'demand': 4.0},
 5: {'cluster': 0.0,
  'longitude': 118.79760149999998,
  'latitude': 32.04245321,
  'demand': 54.0},
 6: {'cluster': 2.0,
  'longitude': 118.77443400000001,
  'latitude': 32.05102604,
  'demand': 78.0},
 7: {'cluster': 1.0,
  'longitude': 118.7820155,
  'latitude': 32.01413968,
  'demand': 14.0},
 8: {'cluster': 2.0,
  'longitude': 118.7828706,
  'latitude': 32.06893876,
  'demand': 3.0},
 9: {'cluster': 0.0,
  'longitude': 118.79801780000001,
  'latitude': 32.05570623,
  'demand': -26.0},
 10: {'cluster': 1.0,
  'longitude': 118.7921929,
  'latitude': 32.03254211,
  'demand': -4.0},
 11: {'cluster': 3

In [66]:
for k in station_info.keys():
    station_info[k]['cluster'] = int(station_info[k]['cluster'])
    station_info[k]['demand'] = int(station_info[k]['demand'])

In [67]:
station_info

{1: {'cluster': 0,
  'longitude': 118.78751640000002,
  'latitude': 32.04975586,
  'demand': 27},
 2: {'cluster': 1,
  'longitude': 118.7798845,
  'latitude': 32.02845916,
  'demand': -7},
 3: {'cluster': 2,
  'longitude': 118.76809159999999,
  'latitude': 32.0665767,
  'demand': 6},
 4: {'cluster': 1,
  'longitude': 118.7977513,
  'latitude': 32.0150942,
  'demand': 4},
 5: {'cluster': 0,
  'longitude': 118.79760149999998,
  'latitude': 32.04245321,
  'demand': 54},
 6: {'cluster': 2,
  'longitude': 118.77443400000001,
  'latitude': 32.05102604,
  'demand': 78},
 7: {'cluster': 1,
  'longitude': 118.7820155,
  'latitude': 32.01413968,
  'demand': 14},
 8: {'cluster': 2,
  'longitude': 118.7828706,
  'latitude': 32.06893876,
  'demand': 3},
 9: {'cluster': 0,
  'longitude': 118.79801780000001,
  'latitude': 32.05570623,
  'demand': -26},
 10: {'cluster': 1,
  'longitude': 118.7921929,
  'latitude': 32.03254211,
  'demand': -4},
 11: {'cluster': 3,
  'longitude': 118.7685186,
  'latitud

In [68]:
cluster_info = {0:[], 1:[], 2:[], 3:[]}
for k in station_info.keys():
    cluster_info[station_info[k]['cluster']].append({'station_id': k, 'longitude': station_info[k]['longitude'], 'latitude': station_info[k]['latitude'], 'demand': station_info[k]['demand']})

In [69]:
cluster_info

{0: [{'station_id': 1,
   'longitude': 118.78751640000002,
   'latitude': 32.04975586,
   'demand': 27},
  {'station_id': 5,
   'longitude': 118.79760149999998,
   'latitude': 32.04245321,
   'demand': 54},
  {'station_id': 9,
   'longitude': 118.79801780000001,
   'latitude': 32.05570623,
   'demand': -26},
  {'station_id': 20,
   'longitude': 118.78829329999999,
   'latitude': 32.04324071,
   'demand': 16},
  {'station_id': 21,
   'longitude': 118.79532520000001,
   'latitude': 32.04872828,
   'demand': -7},
  {'station_id': 29,
   'longitude': 118.8044565,
   'latitude': 32.05240023,
   'demand': 17},
  {'station_id': 40,
   'longitude': 118.79502,
   'latitude': 32.04097895,
   'demand': 85},
  {'station_id': 43,
   'longitude': 118.8016785,
   'latitude': 32.04723072,
   'demand': 22},
  {'station_id': 45,
   'longitude': 118.80554529999999,
   'latitude': 32.05826824,
   'demand': 15},
  {'station_id': 47,
   'longitude': 118.79507199999999,
   'latitude': 32.05246928,
   'demand

In [70]:
len(cluster_info[0])


71

In [71]:
len(cluster_info[1])

98

In [72]:
len(cluster_info[2])


86

In [73]:

initial_bike = pd.read_csv("E:\\bikeshare\\resources\\data_set\\init_24.csv", usecols=[3]).to_numpy()


43

In [89]:
initial_bike = initial_bike.reshape((-1,))

In [90]:
initial_bike

array([ 25,  40,  27,  11,   6,  14,  23, 115,  29,  77,  15,  26,  32,
         5,  22,  10,  59,  26,  44,  38,  56,  19,  13,   0,  20,  72,
        15,  51,   0,  65,  16,  41,   6,  89,  82,  32,  40,   3,  24,
         0,  13,  26,  28,  19,   5,  34,  41,  32,  10,  23,  45,  41,
        56,  61,  57,   0,  19,  53,  15,  26,  28,  39,  41,  24,  18,
        67,  58,  44,   9,  26,  29,  33,  33,  45,  48,   7,  31,  35,
         8,   6,  14,  32,  32,  38,  84,  11,   4,  31,  14,  18,  15,
        47,  30,  47,  66,   6, 137,  46,  38,  37, 138,  60,  51,  39,
        16,  32,  26,   1,  28,  34,  25,  30,  80,  56,  51,  18,  29,
        38,  59,  59,  61,  15,  19,  10,  10,   0,  12,  45,  53,  33,
        28,  30,  44,  59,  53,  19,  41,  42,  51,  29,   3,  37,  21,
        50,  33,  88,  24,  33,  31,   6,  30,  36,  35,  26,  68,  20,
        22,  33,  60,  24,  52,  50,  50,  60,  53,  29,  73,  13,  29,
        77,  80,  37,  82,  53,  23,  50,  56,  40,  32,  35,  5

In [91]:

distance_matrix = pd.read_csv("E:\\bikeshare\\resources\\data_set\\station_dist_matrix_300.csv").to_numpy()

In [92]:
import sys
np.set_printoptions(threshold=sys.maxsize)

distance_matrix

array([[   0.        , 2474.93916716, 2617.12288396, ..., 3105.91979988,
        3281.40240976, 2739.05725067],
       [2474.93916716,    0.        , 4381.78690826, ..., 5336.65664631,
        5295.03413312, 5091.5810579 ],
       [2617.12288396, 4381.78690826,    0.        , ..., 1419.28595767,
         998.02733239, 1675.38934622],
       ...,
       [3105.91979988, 5336.65664631, 1419.28595767, ...,    0.        ,
         712.88981045,  600.04558038],
       [3281.40240976, 5295.03413312,  998.02733239, ...,  712.88981045,
           0.        , 1255.13191809],
       [2739.05725067, 5091.5810579 , 1675.38934622, ...,  600.04558038,
        1255.13191809,    0.        ]])

In [6]:
import numpy as np
station_list = [70,  10,  49,   6,  21, 106]
mylist = np.array(station_list)
s = []
perms = set()
for i in range(25):  # (1) Draw N samples from permutations Universe U (#U = k!)
    while True:  # (2) Endless loop
        perm = np.random.permutation(len(station_list))  # (3) Generate a random permutation form U
        key = tuple(perm)
        # print(mylist[perm] < 0)
        if key not in perms or mylist[perm] < 0:  # (4) Check if permutation already has been drawn (hash table)
            perms.update(key)  # (5) Insert into set
            break  # (6) Break the endless loop
    complete = mylist[perm]
    print(complete)

In [2]:
import numpy as np


In [10]:
a = np.random.choice(2, 1, replace=False)

In [11]:
a

array([0])